// <auto-generated />
using System;
using KasirKu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KasirKu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803124315_UpdateSeedAkun")]
    partial class UpdateSeedAkun
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("KasirKu.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JenisAksi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KasirId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Waktu")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KasirId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("KasirKu.Models.DetailTransaksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HargaJual")
                        .HasColumnType("TEXT");

                    b.Property<int>("Jumlah")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdukId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransaksiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdukId");

                    b.HasIndex("TransaksiId");

                    b.ToTable("DetailTransaksi");
                });

            modelBuilder.Entity("KasirKu.Models.Kasir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kasir");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nama = "Admin KasirKu",
                            PasswordHash = "AQAAAAIAAYagAAAAEO0srbQ83jUrJaGs7LXC/T4XBo4K0PI7tP+OoGJejP6W0lq58QnE0kSeaBXeKMxztw==",
                            Role = "Admin",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Nama = "Kasir",
                            PasswordHash = "AQAAAAIAAYagAAAAEOeir4tK5zQjyy/KQbzKV4ccC5RwGF/rpp1ODlwWGg7bbImiZhL2O9OdDsaj05pJOw==",
                            Role = "Kasir",
                            Username = "Kasir"
                        });
                });

            modelBuilder.Entity("KasirKu.Models.KasirSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatatanSelisih")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KasirId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ModalAwal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SelisihKas")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalTunaiFisik")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTunaiSistem")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WaktuLogin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WaktuLogout")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KasirId");

                    b.HasIndex("ShiftId");

                    b.ToTable("KasirSession");
                });

            modelBuilder.Entity("KasirKu.Models.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HargaBeli")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HargaJual")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SKU")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StokMinimum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Produk");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HargaBeli = 60000m,
                            HargaJual = 68000m,
                            Kategori = "Sembako",
                            Nama = "Beras 5kg",
                            SKU = "BRS01",
                            Stok = 20,
                            StokMinimum = 5
                        },
                        new
                        {
                            Id = 2,
                            HargaBeli = 14000m,
                            HargaJual = 16000m,
                            Kategori = "Sembako",
                            Nama = "Minyak Goreng 1L",
                            SKU = "MYK01",
                            Stok = 30,
                            StokMinimum = 10
                        },
                        new
                        {
                            Id = 3,
                            HargaBeli = 10000m,
                            HargaJual = 12000m,
                            Kategori = "Sembako",
                            Nama = "Tepung Terigu 1kg",
                            SKU = "TPG01",
                            Stok = 30,
                            StokMinimum = 5
                        },
                        new
                        {
                            Id = 4,
                            HargaBeli = 14000m,
                            HargaJual = 15000m,
                            Kategori = "Sembako",
                            Nama = "Tepung Tapioka 1Kg",
                            SKU = "TPG02",
                            Stok = 30,
                            StokMinimum = 10
                        },
                        new
                        {
                            Id = 5,
                            HargaBeli = 3000m,
                            HargaJual = 3500m,
                            Kategori = "Makanan Instan",
                            Nama = "Indomie Goreng 1 Bks",
                            SKU = "IND01",
                            Stok = 80,
                            StokMinimum = 10
                        },
                        new
                        {
                            Id = 6,
                            HargaBeli = 3000m,
                            HargaJual = 3500m,
                            Kategori = "Makanan Instan",
                            Nama = "Indomie Kuah Ayam Bawang 1 Bks",
                            SKU = "IND02",
                            Stok = 80,
                            StokMinimum = 10
                        },
                        new
                        {
                            Id = 7,
                            HargaBeli = 3000m,
                            HargaJual = 3500m,
                            Kategori = "Makanan Instan",
                            Nama = "Mie Sedaap Soto 1 Bks",
                            SKU = "SDP01",
                            Stok = 80,
                            StokMinimum = 10
                        },
                        new
                        {
                            Id = 8,
                            HargaBeli = 2000m,
                            HargaJual = 2500m,
                            Kategori = "Penyedap",
                            Nama = "Garam Daun 250g",
                            SKU = "GRM01",
                            Stok = 30,
                            StokMinimum = 5
                        },
                        new
                        {
                            Id = 9,
                            HargaBeli = 13200m,
                            HargaJual = 14000m,
                            Kategori = "Penyedap",
                            Nama = "Sasa Penyedap Rasa 250g",
                            SKU = "SSA01",
                            Stok = 50,
                            StokMinimum = 10
                        });
                });

            modelBuilder.Entity("KasirKu.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAktif")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("JamMulai")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("JamSelesai")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaShift")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shift");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAktif = true,
                            JamMulai = new TimeSpan(0, 6, 0, 0, 0),
                            JamSelesai = new TimeSpan(0, 12, 0, 0, 0),
                            NamaShift = "Shift Pagi"
                        },
                        new
                        {
                            Id = 2,
                            IsAktif = true,
                            JamMulai = new TimeSpan(0, 12, 0, 0, 0),
                            JamSelesai = new TimeSpan(0, 17, 0, 0, 0),
                            NamaShift = "Shift Siang"
                        },
                        new
                        {
                            Id = 3,
                            IsAktif = true,
                            JamMulai = new TimeSpan(0, 17, 0, 0, 0),
                            JamSelesai = new TimeSpan(0, 22, 0, 0, 0),
                            NamaShift = "Shift Sore/Malam"
                        },
                        new
                        {
                            Id = 4,
                            IsAktif = false,
                            JamMulai = new TimeSpan(0, 22, 0, 0, 0),
                            JamSelesai = new TimeSpan(0, 6, 0, 0, 0),
                            NamaShift = "Shift Malam (24 Jam)"
                        });
                });

            modelBuilder.Entity("KasirKu.Models.Transaksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KasirSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kembalian")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaKasir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomorNota")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalBayar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KasirSessionId");

                    b.ToTable("Transaksi");
                });

            modelBuilder.Entity("KasirKu.Models.AuditLog", b =>
                {
                    b.HasOne("KasirKu.Models.Kasir", "Kasir")
                        .WithMany()
                        .HasForeignKey("KasirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kasir");
                });

            modelBuilder.Entity("KasirKu.Models.DetailTransaksi", b =>
                {
                    b.HasOne("KasirKu.Models.Produk", "Produk")
                        .WithMany()
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KasirKu.Models.Transaksi", "Transaksi")
                        .WithMany("DetailTransaksi")
                        .HasForeignKey("TransaksiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produk");

                    b.Navigation("Transaksi");
                });

            modelBuilder.Entity("KasirKu.Models.KasirSession", b =>
                {
                    b.HasOne("KasirKu.Models.Kasir", "Kasir")
                        .WithMany()
                        .HasForeignKey("KasirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KasirKu.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.Navigation("Kasir");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("KasirKu.Models.Transaksi", b =>
                {
                    b.HasOne("KasirKu.Models.KasirSession", "KasirSession")
                        .WithMany("TransaksiList")
                        .HasForeignKey("KasirSessionId");

                    b.Navigation("KasirSession");
                });

            modelBuilder.Entity("KasirKu.Models.KasirSession", b =>
                {
                    b.Navigation("TransaksiList");
                });

            modelBuilder.Entity("KasirKu.Models.Transaksi", b =>
                {
                    b.Navigation("DetailTransaksi");
                });
#pragma warning restore 612, 618
        }
    }
}
